name: Other
description: If you have a question, a suggestion, or anything that is not a bug report and not a feature request.
assignees:
    - racz16
body:
    - type: textarea
      id: description
      attributes:
          label: Description
      validations:
          required: true
